# Generated by Django 3.2.4 on 2021-07-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('m_name', models.CharField(max_length=100, verbose_name='Middle Name')),
                ('f_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('gender', models.CharField(max_length=100, verbose_name='Gender')),
                ('date_of_birth', models.CharField(max_length=100, verbose_name='Date of Birth')),
                ('school', models.CharField(max_length=100, verbose_name='School')),
                ('classification', models.CharField(max_length=50, verbose_name='Classification')),
                ('sport', models.CharField(max_length=50, verbose_name='Sport')),
                ('position', models.CharField(max_length=60, verbose_name='Position')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('address_1', models.CharField(max_length=100, verbose_name='Address 1')),
                ('address_2', models.CharField(max_length=100, verbose_name='Address 2')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zipcode', models.CharField(max_length=100, verbose_name='Zipcode')),
                ('sport_background', models.TextField(max_length=300, verbose_name='Please Describe Your Sport Background')),
                ('sport_play', models.TextField(max_length=200, verbose_name='What Other Sports You have Played in the Past')),
                ('dominant_hand', models.CharField(max_length=100, verbose_name='What is Your Dominant Hand')),
                ('programs', models.CharField(max_length=100, verbose_name='Please Choose Program(s) You are Interested')),
            ],
        ),
    ]
